# Generated by Django 2.2 on 2020-05-23 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MqttData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=100, verbose_name='话题')),
                ('msg', models.CharField(max_length=300, verbose_name='消息')),
            ],
        ),
    ]
